// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccczsnqqtqzrjlggpmqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjY3pzbnFxdHF6cmpsZ2dwbXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjAzMTgsImV4cCI6MjA2NzEzNjMxOH0.bJz-ChROoFyeXv_N6-WaNPDMRnocOdQPDQ-Qn4zfQAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});